services:

  wekandb:
    container_name: wekan-db
    image: ghcr.io/ferretdb/all-in-one
    restart: on-failure
    # Opening port to outside:
    ports:
      - 27017:27017
    # Not only exposing port at internal Docker network:
    #expose:
    #  - 27017
    networks:
      - wekan-tier
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data:/data/ferretdb-postgresql
      - wekan-db-dump:/data/ferretdb-postgresql-dump
    environment:
      - DOCKER_DEFAULT_PLATFORM=linux/x86_64/v8
      - FERRETDB_HANDLER=postgresql
      - FERRETDB_REPL_SET_NAME=rs0
      - FERRETDB_TELEMETRY=disable

  # Creating OpLog collection to local db:
  wekandb-oplog-setup:
    image: ghcr.io/ferretdb/all-in-one
    restart: no
    depends_on:
      - wekandb
    entrypoint: [ "bash", "-c", "sleep 10 && /usr/bin/mongosh --host wekandb:27017 --eval 'use local;db.createCollection('oplog.rs', { capped: true, size: 536870912 });'"]

volumes:
  wekan-files:
    driver: local
  data:
    driver: local
  wekan-db-dump:
    driver: local

networks:
  wekan-tier:
    driver: bridge
